# Generated by Django 3.1.2 on 2020-11-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndoreJobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desgn', models.CharField(max_length=30)),
                ('openings', models.IntegerField()),
                ('location', models.CharField(max_length=40)),
                ('qual', models.CharField(max_length=40)),
                ('exp', models.CharField(max_length=20)),
                ('contract', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40)),
            ],
        ),
    ]
